### ISSUE TITLE
Not getting proper results

### ISSUE THREAD

**Issue by hamzaaslam0497** [iam-mhaseeb/Python-Implementation-of-LSA#2]
I execute that code on files by reading files and storing in list which is document[] and then where you define new_doc , i take input from the user using input() and assign to new_doc but when i execute that program it shows me wrong result 
your code shows me a list with file index and their weight but not the write one on top neither in top 10

**Comment by iam-mhaseeb** [comment]
Oh dear! It needs a proper debugging of your data and representation of your data.

**Comment by iam-mhaseeb** [comment]
Closing this issue.
